In [1]:
pip install pyyaml

Requirement already satisfied: pyyaml in c:\users\hp\anaconda3\lib\site-packages (6.0.1)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import yaml

In [4]:
with open("C:\\Data science\\Project 2 - data driven stock analysis\\data\\2023-10\\2023-10-03_05-30-00.yaml","r") as file:
    data = yaml.safe_load(file)

In [5]:
import pandas as pd

df = pd.DataFrame(data)
df

,Ticker,close,date,high,low,month,open,volume
0,SBIN,602.95,2023-10-03 05:30:00,604.90,589.60,2023-10,596.60,15322196
1,BAJFINANCE,7967.60,2023-10-03 05:30:00,7975.50,7755.00,2023-10,7780.80,944555
2,TITAN,3196.25,2023-10-03 05:30:00,3212.50,3114.40,2023-10,3148.80,1007308
3,ITC,439.75,2023-10-03 05:30:00,442.90,439.25,2023-10,441.00,7481883
4,TCS,3513.85,2023-10-03 05:30:00,3534.20,3480.10,2023-10,3534.20,1948148
5,LT,3073.25,2023-10-03 05:30:00,3077.45,2995.10,2023-10,3040.50,3254492
6,TATACONSUM,861.20,2023-10-03 05:30:00,868.75,853.49,2023-10,859.32,1168848
7,RELIANCE,1159.08,2023-10-03 05:30:00,1167.80,1158.00,2023-10,1164.97,8859056
8,HCLTECH,1238.70,2023-10-03 05:30:00,1256.70,1222.70,2023-10,1232.50,2162636
9,JSWSTEEL,770.25,2023-10-03 05:30:00,776.55,768.00,2023-10,776.55,1099773
10,ULTRACEMCO,8304.90,2023-10-03 05:30:00,8377.00,8221.20,2023-10,8289.00,454402
11,POWERGRID,199.55,2023-10-03 05:30:00,200.00,196.90,2023-10,198.75,10830728
12,INFY,1434.00,2023-10-03 05:30:00,1437.00,1420.30,2023-10,1436.05,4181867
13,TRENT,2059.10,2023-10-03 05:30:00,2086.30,2052.00,2023-10,2074.30,543387
14,BHARTIARTL,925.30,2023-10-03 05:30:00,928.25,916.05,2023-10,918.25,4338272
15,TATAMOTORS,620.45,2023-10-03 05:30:00,632.65,618.60,2023-10,632.60,6894577
16,WIPRO,405.45,2023-10-03 05:30:00,408.10,403.60,2023-10,406.45,2864052
17,TECHM,1216.20,2023-10-03 05:30:00,1230.70,1212.55,2023-10,1220.60,1622290
18,NTPC,241.20,2023-10-03 05:30:00,246.70,240.55,2023-10,244.35,14885044
19,HINDUNILVR,2468.90,2023-10-03 05:30:00,2499.00,2461.80,2023-10,2490.00,1585626
20,APOLLOHOSP,5118.95,2023-10-03 05:30:00,5154.95,5066.00,2023-10,5138.95,268482
21,M&M,1537.40,2023-10-03 05:30:00,1598.00,1533.05,2023-10,1597.20,3436776
22,GRASIM,1913.84,2023-10-03 05:30:00,1931.32,1899.10,2023-10,1920.46,591326
23,ICICIBANK,940.30,2023-10-03 05:30:00,951.60,939.00,2023-10,951.60,11131636
24,ADANIENT,2387.25,2023-10-03 05:30:00,2424.90,2372.00,2023-10,2418.00,2019899
25,ADANIPORTS,831.40,2023-10-03 05:30:00,836.75,824.25,2023-10,826.00,2453090
26,BEL,139.20,2023-10-03 05:30:00,140.60,137.20,2023-10,137.90,19010910
27,BAJAJFINSV,1561.05,2023-10-03 05:30:00,1564.20,1527.00,2023-10,1530.25,1083086
28,EICHERMOT,3351.40,2023-10-03 05:30:00,3434.95,3302.90,2023-10,3426.90,1354075
29,COALINDIA,291.90,2023-10-03 05:30:00,297.10,290.10,2023-10,297.05,9348540
30,MARUTI,10346.90,2023-10-03 05:30:00,10709.80,10303.30,2023-10,10709.80,623006
31,INDUSINDBK,1435.40,2023-10-03 05:30:00,1438.40,1420.00,2023-10,1432.00,1442499
32,ASIANPAINT,3166.85,2023-10-03 05:30:00,3227.80,3162.00,2023-10,3166.10,1219145
33,TATASTEEL,128.00,2023-10-03 05:30:00,129.10,127.25,2023-10,129.00,18613557
34,HDFCLIFE,633.55,2023-10-03 05:30:00,637.50,628.55,2023-10,634.45,3454441
35,DRREDDY,1092.34,2023-10-03 05:30:00,1117.38,1090.00,2023-10,1117.38,2065240
36,SUNPHARMA,1141.45,2023-10-03 05:30:00,1161.95,1139.25,2023-10,1159.55,1946966
37,KOTAKBANK,1727.05,2023-10-03 05:30:00,1735.00,1715.45,2023-10,1730.00,5534869
38,SHRIRAMFIN,1921.95,2023-10-03 05:30:00,1939.90,1881.00,2023-10,1938.00,2207907
39,NESTLEIND,2231.52,2023-10-03 05:30:00,2259.47,2225.52,2023-10,2250.69,500130
40,ONGC,184.60,2023-10-03 05:30:00,189.30,183.65,2023-10,189.30,22118500
41,CIPLA,1182.80,2023-10-03 05:30:00,1185.70,1170.95,2023-10,1184.00,1581125
42,BPCL,170.68,2023-10-03 05:30:00,174.60,170.43,2023-10,174.25,10514554
43,BRITANNIA,4495.45,2023-10-03 05:30:00,4553.25,4486.60,2023-10,4524.80,543482
44,SBILIFE,1292.45,2023-10-03 05:30:00,1302.15,1282.65,2023-10,1302.15,1282289
45,HINDALCO,479.95,2023-10-03 05:30:00,484.55,476.60,2023-10,483.10,4657602
46,HEROMOTOCO,3015.60,2023-10-03 05:30:00,3064.90,2991.50,2023-10,3058.00,387906
47,AXISBANK,1041.05,2023-10-03 05:30:00,1044.70,1032.60,2023-10,1035.00,11589322
48,HDFCBANK,1508.05,2023-10-03 05:30:00,1527.00,1506.00,2023-10,1527.00,19485847
49,BAJAJ-AUTO,5016.45,2023-10-03 05:30:00,5073.00,4997.10,2023-10,5065.00,464531

In [6]:
import os

In [9]:
folder_path = "C:\\Data science\\Project 2 - data driven stock analysis\\data\\2023-10"
oct_data =[]
for filename in os.listdir(folder_path):
    if filename.endswith(".yaml"):
        file_path = os.path.join(folder_path, filename)
        with open(file_path, 'r') as file:
            data = yaml.safe_load(file)
            if isinstance(data, list):
                oct_data.extend(data)
            elif isinstance(data, dict):
                oct_data.append(data)

df_oct = pd.DataFrame(oct_data)

In [10]:
df_oct

,Ticker,close,date,high,low,month,open,volume
0,SBIN,602.95,2023-10-03 05:30:00,604.90,589.60,2023-10,596.60,15322196
1,BAJFINANCE,7967.60,2023-10-03 05:30:00,7975.50,7755.00,2023-10,7780.80,944555
2,TITAN,3196.25,2023-10-03 05:30:00,3212.50,3114.40,2023-10,3148.80,1007308
3,ITC,439.75,2023-10-03 05:30:00,442.90,439.25,2023-10,441.00,7481883
4,TCS,3513.85,2023-10-03 05:30:00,3534.20,3480.10,2023-10,3534.20,1948148
...,...,...,...,...,...,...,...,...
995,HINDALCO,459.50,2023-10-31 05:30:00,465.00,453.25,2023-10,465.00,5236060
996,HEROMOTOCO,3088.35,2023-10-31 05:30:00,3139.60,3080.15,2023-10,3115.05,207132
997,AXISBANK,981.85,2023-10-31 05:30:00,998.00,978.00,2023-10,998.00,7816805
998,HDFCBANK,1476.50,2023-10-31 05:30:00,1504.00,1474.00,2023-10,1504.00,16317412
999,BAJAJ-AUTO,5314.05,2023-10-31 05:30:00,5366.15,5292.60,2023-10,5340.00,400987

In [14]:
folder_path = "C:\\Data science\\Project 2 - data driven stock analysis\\data"
all_data = []
for root, dirs, files in os.walk(folder_path):
    for filename in files:
        if filename.endswith('.yaml') or filename.endswith('.yml'):
            file_path = os.path.join(root, filename)
            with open(file_path, 'r') as file:
                data = yaml.safe_load(file)
                if isinstance(data, list):
                    all_data.extend(data)
                elif isinstance(data, dict):
                    all_data.append(data)

df_all = pd.DataFrame(all_data)

In [15]:
df_all

,Ticker,close,date,high,low,month,open,volume
0,SBIN,602.95,2023-10-03 05:30:00,604.9,589.60,2023-10,596.60,15322196
1,BAJFINANCE,7967.60,2023-10-03 05:30:00,7975.5,7755.00,2023-10,7780.80,944555
2,TITAN,3196.25,2023-10-03 05:30:00,3212.5,3114.40,2023-10,3148.80,1007308
3,ITC,439.75,2023-10-03 05:30:00,442.9,439.25,2023-10,441.00,7481883
4,TCS,3513.85,2023-10-03 05:30:00,3534.2,3480.10,2023-10,3534.20,1948148
...,...,...,...,...,...,...,...,...
14195,HINDALCO,652.10,2024-11-22 05:30:00,657.3,647.40,2024-11,652.95,3586402
14196,HEROMOTOCO,4794.10,2024-11-22 05:30:00,4808.4,4742.00,2024-11,4778.40,394712
14197,AXISBANK,1142.40,2024-11-22 05:30:00,1147.9,1127.55,2024-11,1136.65,16687505
14198,HDFCBANK,1745.60,2024-11-22 05:30:00,1754.3,1729.55,2024-11,1743.55,12386806
14199,BAJAJ-AUTO,9481.65,2024-11-22 05:30:00,9602.9,9444.10,2024-11,9545.00,619823

In [16]:
df_all.to_csv("combined_all.csv")